import Head from "next/head";

import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar/Navbar";
import Sidebar from "@/components/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>FreePicks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Navbar />
        <div className="w-full grid grid-cols-20 gap-10">
          {/* Spacer */}
          <div className="col-span-1" />

          <div className="col-span-4 justify-self-end">
            <Sidebar />
          </div>

          {/* Main */}
          <div className="col-span-10">Main</div>

          {/* Bet Slip */}
          <div className="col-span-4 justify-self-start">Bet Slip</div>

          {/* Spacer */}
          <div className="col-span-1" />
        </div>
      </div>
    </>
  );
}
