import Head from "next/head";

import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Main from "@/layouts/Main/Main";
import Navbar from "@/components/Navbar/Navbar";
import Sidebar from "@/layouts/Sidebar/Sidebar";
import BetSlip from "@/components/PickSlip/PickSlip";
import Footer from "@/layouts/Footer/Footer";
import ContentLayout from "@/components/ContentLayout/Content";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

function Home() {
  return (
    <>
      <Head>
        <title>FreePicks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Navbar />

        <ContentLayout
          containerStyles="w-full h-full mt-8"
          contentLeft={<Sidebar />}
          contentCenter={<Main />}
          contentRight={<BetSlip />}
        />
      </div>
      <Footer />
    </>
  );
}

export default Home;
